// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXggGzUpNory1l91Uqrrmtnyb0OVKb_gk',
    appId: '1:568907990541:web:b155302fe216b7ecd77744',
    messagingSenderId: '568907990541',
    projectId: 'englishlearningapp-58ff6',
    authDomain: 'englishlearningapp-58ff6.firebaseapp.com',
    storageBucket: 'englishlearningapp-58ff6.firebasestorage.app',
    measurementId: 'G-W5ZG4DVJZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9-u3zta7TIyt6ytjRS7jt4MUQLGT5n5o',
    appId: '1:568907990541:android:6a189ce367c77558d77744',
    messagingSenderId: '568907990541',
    projectId: 'englishlearningapp-58ff6',
    storageBucket: 'englishlearningapp-58ff6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOcwtTB5330yys6NRzTFtI7PaKYdD9UF4',
    appId: '1:568907990541:ios:65083f1774f6217cd77744',
    messagingSenderId: '568907990541',
    projectId: 'englishlearningapp-58ff6',
    storageBucket: 'englishlearningapp-58ff6.firebasestorage.app',
    iosBundleId: 'com.example.wordVault',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOcwtTB5330yys6NRzTFtI7PaKYdD9UF4',
    appId: '1:568907990541:ios:65083f1774f6217cd77744',
    messagingSenderId: '568907990541',
    projectId: 'englishlearningapp-58ff6',
    storageBucket: 'englishlearningapp-58ff6.firebasestorage.app',
    iosBundleId: 'com.example.wordVault',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXggGzUpNory1l91Uqrrmtnyb0OVKb_gk',
    appId: '1:568907990541:web:449e6b19ddb8883fd77744',
    messagingSenderId: '568907990541',
    projectId: 'englishlearningapp-58ff6',
    authDomain: 'englishlearningapp-58ff6.firebaseapp.com',
    storageBucket: 'englishlearningapp-58ff6.firebasestorage.app',
    measurementId: 'G-KJF3YZEH49',
  );
}
